name: harvestor
description: Harvester Monitoring App (Flutter + Firebase)
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  firebase_core: ^3.4.0
  firebase_auth: ^5.1.2
  firebase_database: ^11.1.3
  firebase_messaging: ^15.0.3
  provider: ^6.0.5
  fl_chart: ^0.68.0
  sleek_circular_slider: ^2.0.1
  shared_preferences: ^2.2.3
  intl: ^0.19.0
  flutter_local_notifications: ^17.2.1
  pdf: ^3.10.7
  printing: ^5.13.1
  google_sign_in: ^6.2.1
  barcode_scan2: ^4.3.0
  qr_flutter: ^4.1.0
  package_info_plus: ^8.0.2
  google_fonts: ^6.2.1
  cloud_functions: ^5.0.4
  url_launcher: ^6.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
